import pytest
import numpy as np
from cgexplore.molecule_construction import (
    FourC0Arm,
    FourC1Arm,
    ThreeC0Arm,
    ThreeC1Arm,
    ThreeC2Arm,
    TwoC0Arm,
    TwoC1Arm,
    TwoC2Arm,
    TwoC3Arm,
)
from cgexplore.beads import CgBead

from .case_data import CaseData

# Three tests cases with four atoms with known bond lengths,
# angles and torsions.


@pytest.fixture(
    params=(
        lambda name: CaseData(
            precursor=FourC0Arm(
                bead=CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=4,
                ),
            ),
            precursor_name="4C0c0100",
            bead_set={
                "c0100": CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=4,
                )
            },
            smiles="Br[Ag](Br)(Br)Br",
            position_matrix=np.array(
                [
                    [-2.0, 0.0, -1.0],
                    [0.0, 0.0, 1.0],
                    [0.0, -2.0, -1.0],
                    [2.0, 0.0, 1.0],
                    [0.0, 2.0, 1.0],
                ]
            ),
            num_fgs=4,
            name=name,
        ),
        lambda name: CaseData(
            precursor=FourC1Arm(
                bead=CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=4,
                ),
                abead1=CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            ),
            precursor_name="4C1c0100p0220",
            bead_set={
                "c0100": CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=4,
                ),
                "p0220": CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            },
            smiles="[P][Ag@SP1]([P])([P])[P]",
            position_matrix=np.array(
                [
                    [0.0, 0.0, 1.6],
                    [12.0, 0.0, 0.0],
                    [0.0, 12.0, 0.0],
                    [-12.0, 0.0, 0.0],
                    [0.0, -12.0, 0.0],
                ]
            ),
            num_fgs=4,
            name=name,
        ),
        lambda name: CaseData(
            precursor=ThreeC0Arm(
                bead=CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=3,
                ),
            ),
            precursor_name="3C0c0100",
            bead_set={
                "c0100": CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=3,
                ),
            },
            smiles="Br[Ag](Br)Br",
            position_matrix=np.array(
                [
                    [-2, 0, 0],
                    [0, 0, 0],
                    [-1.2, 1, 0],
                    [-1.2, -1, 0],
                ]
            ),
            num_fgs=3,
            name=name,
        ),
        lambda name: CaseData(
            precursor=ThreeC1Arm(
                bead=CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=3,
                ),
                abead1=CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            ),
            precursor_name="3C1c0100p0220",
            bead_set={
                "c0100": CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=3,
                ),
                "p0220": CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            },
            smiles="[P][Ag]([P])[P]",
            position_matrix=np.array(
                [
                    [1.1, 0.0, 0.0],
                    [6.0, 0.0, 1.5],
                    [-3.6, 3.0, 1.5],
                    [-3.6, -3.0, 1.5],
                ]
            ),
            num_fgs=3,
            name=name,
        ),
        lambda name: CaseData(
            precursor=ThreeC2Arm(
                bead=CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=3,
                ),
                abead1=CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                abead2=CgBead(
                    element_string="N",
                    bead_type="n0301",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            ),
            precursor_name="3C2c0100p0220n0301",
            bead_set={
                "c0100": CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=3,
                ),
                "p0220": CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                "n0301": CgBead(
                    element_string="N",
                    bead_type="n0301",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            },
            smiles="[N][P][Ag]([P][N])[P][N]",
            position_matrix=np.array(
                [
                    [1.1, 0.0, 0.0],
                    [12.0, 0.0, 3.0],
                    [-7.2, 6.0, 3.0],
                    [-7.2, -6.0, 3.0],
                    [24.0, 0.0, 0.0],
                    [-14.4, 12.0, 0.0],
                    [-14.4, -12.0, 0.0],
                ]
            ),
            num_fgs=3,
            name=name,
        ),
        lambda name: CaseData(
            precursor=TwoC0Arm(
                bead=CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            ),
            precursor_name="2C0c0100",
            bead_set={
                "c0100": CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            },
            smiles="Br[Ag]Br",
            position_matrix=np.array(
                [
                    [-3, 0, 0],
                    [0, 0, 0],
                    [3, 0, 0],
                ]
            ),
            num_fgs=2,
            name=name,
        ),
        lambda name: CaseData(
            precursor=TwoC1Arm(
                bead=CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                abead1=CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            ),
            precursor_name="2C1c0100p0220",
            bead_set={
                "c0100": CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                "p0220": CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            },
            smiles="[P][Ag][P]",
            position_matrix=np.array(
                [
                    [-1.5, 0, 0],
                    [13.5, 0, 0],
                    [6.0, 0, 0],
                ]
            ),
            num_fgs=2,
            name=name,
        ),
        lambda name: CaseData(
            precursor=TwoC2Arm(
                bead=CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                abead1=CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                abead2=CgBead(
                    element_string="N",
                    bead_type="n0301",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            ),
            precursor_name="2C2c0100p0220n0301",
            bead_set={
                "c0100": CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                "p0220": CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                "n0301": CgBead(
                    element_string="N",
                    bead_type="n0301",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            },
            smiles="[N][P][Ag][P][N]",
            position_matrix=np.array(
                [
                    [-1.5, 0, 0],
                    [25.5, 0, 0],
                    [6.0, 0, 0],
                    [18.0, 0, 0],
                    [12.0, 0, 0],
                ]
            ),
            num_fgs=2,
            name=name,
        ),
        lambda name: CaseData(
            precursor=TwoC3Arm(
                bead=CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                abead1=CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                abead2=CgBead(
                    element_string="N",
                    bead_type="n0301",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                abead3=CgBead(
                    element_string="C",
                    bead_type="a0111",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            ),
            precursor_name="2C3c0100p0220n0301a0111",
            bead_set={
                "c0100": CgBead(
                    element_string="Ag",
                    bead_type="c0100",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                "p0220": CgBead(
                    element_string="P",
                    bead_type="p0220",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                "n0301": CgBead(
                    element_string="N",
                    bead_type="n0301",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
                "a0111": CgBead(
                    element_string="C",
                    bead_type="a0111",
                    bond_r=1,
                    bond_k=1,
                    angle_centered=1,
                    angle_k=1,
                    sigma=1,
                    epsilon=1,
                    coordination=2,
                ),
            },
            smiles="[C][N][P][Ag][P][N][C]",
            position_matrix=np.array(
                [
                    [-1.5, 0, 0],
                    [37.5, 0, 0],
                    [6.0, 0, 0],
                    [30.0, 0, 0],
                    [12.0, 0, 0],
                    [24, 0, 0],
                    [18, 0, 0],
                ]
            ),
            num_fgs=2,
            name=name,
        ),
    )
)
def precursor(request: pytest.FixtureRequest) -> CaseData:
    return request.param(
        f"{request.fixturename}{request.param_index}",
    )
