version: 2

build:
    os: ubuntu-22.04
    tools:
      python: "mambaforge-22.9"

sphinx:
    configuration: docs/source/conf.py

conda:
  environment: rtd311.yml

python:
    install:
        - method: pip
          path: .
          extra_requirements:
            - dev
