version: 2

build:
    os: ubuntu-lts-latest
    tools:
        python: "3.13"

sphinx:
    configuration: docs/source/conf.py

python:
    install:
        - method: pip
          path: .
          extra_requirements:
              - dev
