name: test
channels:
  - conda-forge
dependencies:
  - pip:
      - alabaster==0.7.13
      - atomlite==3.0.1
      - babel==2.12.1
      - black==23.7.0
      - bleach==6.0.0
      - build==0.10.0
      - certifi==2023.7.22
      - cffi==1.15.1
      - ciso8601==2.3.0
      - click==8.1.6
      - contourpy==1.1.0
      - coverage==7.2.7
      - cryptography==41.0.2
      - cycler==0.11.0
      - dill==0.3.7
      - dnspython==2.4.1
      - docutils==0.20.1
      - fonttools==4.41.1
      - glob2==0.7
      - imagesize==1.4.1
      - iniconfig==2.0.0
      - jaraco-classes==3.3.0
      - jeepney==0.8.0
      - jinja2==3.1.2
      - joblib==1.3.1
      - keyring==24.2.0
      - kiwisolver==1.4.4
      - lxml==4.9.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mchammer==1.0.4
      - mdurl==0.1.2
      - moldoc==3.0.0
      - more-itertools==10.0.0
      - multiprocess==0.70.15
      - mypy==1.4.1
      - mypy-extensions==1.0.0
      - networkx==3.1
      - numpy==1.25.1
      - orjson==3.9.2
      - pathos==0.3.1
      - pathspec==0.11.1
      - pillow==10.0.0
      - pip-tools==7.1.0
      - pkginfo==1.9.6
      - pluggy==1.2.0
      - pox==0.3.3
      - ppft==1.7.6.7
      - pycparser==2.21
      - pygments==2.15.1
      - pymongo==4.4.1
      - pyparsing==3.0.9
      - pyproject-hooks==1.0.0
      - pytest==7.4.0
      - pytest-benchmark==4.0.0
      - pytest-cov==4.1.0
      - pytest-datadir==1.4.1
      - pytest-lazy-fixture==0.6.3
      - pyyaml==6.0.1
      - rdkit==2023.3.2
      - readme-renderer==40.0
      - requests-toolbelt==1.0.0
      - requests-viewer==0.0.12
      - rfc3986==2.0.0
      - rich==13.4.2
      - ruff==0.0.280
      - scikit-learn==1.3.0
      - seaborn==0.12.2
      - secretstorage==3.3.3
      - snowballstemmer==2.2.0
      - sphinx==7.1.0
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - spindry==0.0.91
      - stk==2023.7.19.1
      - stko==0.0.40
      - threadpoolctl==3.2.0
      - twine==4.0.2
      - vabene==0.0.5
      - webencodings==0.5.1
